service: back-end
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  iam: 
    role:
      statements:
        - Effect: Allow
          Action: cognito-idp:adminCreateUser
          Resource: arn:aws:cognito-idp:us-east-1:945464918858:userpool/us-east-1_aELCHI62m
  environment:
    DB_USER: admin
    DB_PWD: +wse4rftgy7ujiko0p-[
    DB_NAME: dbprojectio
    DB_HOST: mysqlserver.cntgvyhxhz7f.us-east-1.rds.amazonaws.com
    DB_PORT: 3306

functions:
  CreateUser:
    handler: src/user/create/handler.main
    events:
      - http:
          path: /user
          method: post
          cors: true
  CreateProject:
    handler: src/project/create/handler.main
    events:
      - http:
          path: /project
          method: post
          cors: true
  CreateTheme:
    handler: src/theme/create/handler.main
    events:
      - http:
          path: /theme
          method: post
          cors: true
  CreateSubject:
    handler: src/subject/create/handler.main
    events:
      - http:
          path: /subject
          method: post
          cors: true
  ListSubjects:
    handler: src/subject/list/handler.main
    events:
      - http:
          path: /subject
          method: get
          cors: true
  ListThemes:
    handler: src/theme/list/handler.main
    events:
      - http:
          path: /theme
          method: get
          cors: true
  CreateLessonLearned:
    handler: src/lessonLearned/create/handler.main
    events:
      - http:
          path: /lessonLearned
          method: post
          cors: true
  EditLessonLearned:
    handler: src/lessonLearned/edit/handler.main
    events:
      - http:
          path: /lessonLearned
          method: put
          cors: true
  DeleteLessonLearned:
    handler: src/lessonLearned/delete/handler.main
    events:
      - http:
          path: /lessonLearned
          method: delete
          cors: true
  DeleteProject:
    handler: src/project/delete/handler.main
    events:
      - http:
          path: /project
          method: delete
          cors: true
  EditProject:
    handler: src/project/edit/handler.main
    events:
      - http:
          path: /project
          method: put
          cors: true
  GetProject:
    handler: src/project/get/handler.main
    events:
      - http:
          path: /project
          method: get
          cors: true
  SearchProject:
    handler: src/project/search/handler.main
    events:
      - http:
          path: /project
          method: get
          cors: true
  CreateComment:
    handler: src/comment/create/handler.main
    events:
      - http:
          path: /comment
          method: post
          cors: true

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: projectio
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    DocumentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: projectio-documents-bucket